/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
#if 0
	__asm volatile ("ldr r1, =#0x20001000");
	__asm volatile ("ldr r2, =#0x20001004");
	__asm volatile ("ldr r0, [r1]");
	__asm volatile ("ldr r1, [r2]");
	__asm volatile ("add r0, r0 , r1");
	__asm volatile ("str r0, [r2]");
#endif

	/*Check the disassembly for these lines of code in
	 * list file*/
	int val = 0x50;
	__asm volatile ("mov r0, %0": : "r"(val));
	__asm volatile ("mov r0, %0": : "r"(0x48));
	__asm volatile ("mov r0, %0": : "i"(0x48));

	int control_reg;
	/*copy from CONTROL reg to control_reg*/
	__asm volatile ("mrs %0, CONTROL" : "=r"(control_reg));

	int p1, *p2;

	p2 = (int*)0x20000008U;
	__asm volatile ("ldr %0, [%1]": "=r"(p1): "r"(p2)); //p1 = *p2
	/* Loop forever */
	for(;;);
}
